/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import static quizapp.QuizFrame.answers;
import static quizapp.QuizFrame.group;
import static quizapp.QuizFrame.page;
import static quizapp.QuizFrame.questions;
import static quizapp.QuizFrame.result;

/**
 *
 * @author KairaMGotze
 */
public class QuizFrame2 extends javax.swing.JFrame implements ActionListener{

      public static   String[][] questions = new String[5][5];
       public static int[] answers = new int[5];
      
       public static int page = 0 ;
       public static int result  = 0;
       boolean[] srabotalo = new boolean[5];
boolean[] correct = new boolean[5];


    /**
     * Creates new form NewJFrame
     */
              public void setBools1()
       {
           srabotalo[0] = false;
           srabotalo[1] = false;
           srabotalo[2] = false;
           srabotalo[3] = false;
           srabotalo[4] = false;


       }
         public void setCorrects1()
       {
           correct[0] = false;
           correct[1] = false;
           correct[2] = false;
           correct[3] = false;
           correct[4] = false;


       }
       public void getAnswers1()
       {
           answers[0] = 3;
           answers[1] = 3;
           answers[2] = 4;
           answers[3] = 1;
           answers[4] = 3;


       }
       public void FullArray1()
       {
          questions[0][0] = "1";
          questions[0][1] = "Conf";
          questions[0][2] = "In";
          questions[0][3] = "Bot";
          questions[0][4] = "Ma";

          questions[1][0] = "What is a Software ?";
          questions[1][1] = "Software is set of programs";
          questions[1][2] = "Software is documentation and configuration of data";
          questions[1][3] = "Software is set of programs, documentation & configuration of data";
          questions[1][4] = "None of the mentioned";

          questions[2][0] = "What are attributes of good software?";
          questions[2][1] = "Software maintainability";
          questions[2][2] = "Software functionality";
          questions[2][3] = "Software development";
          questions[2][4] = "Software maintainability & functionality";

          questions[3][0] = "Which of these software engineering activities are not a part of software processes";
          questions[3][1] = "Software dependence";
          questions[3][2] = "Software development";
          questions[3][3] = "Software validation";
          questions[3][4] = "Software specification";

          questions[4][0] = "Which of these does not account for software failure?";
          questions[4][1] = "Increasing Demand";
          questions[4][2] = "Low expectation";
          questions[4][3] = "Increasing Supply";
          questions[4][4] = "Less reliable and expensive";

       }
    public QuizFrame2() {
        initComponents();
        group.add(jRadioButton1);
                group.add(jRadioButton5);
                group.add(jRadioButton6);
                group.add(jRadioButton7);
                jRadioButton1.addActionListener(this);
                jRadioButton5.addActionListener(this);
                jRadioButton6.addActionListener(this);
                jRadioButton7.addActionListener(this);
                jButton1.addActionListener(this);

FullArray1();
getAnswers1();
setThisText1(page);
setBools1();
setCorrects1();

    }
public  void setThisText1(int i)
    {
        String [] hey = new String[5];
        hey[0]=questions[i][0];
        hey[1]=questions[i][1];
        hey[2]=questions[i][2];
        hey[3]=questions[i][3];
        hey[4]=questions[i][4];
            jTextField1.setText(hey[0]);
          jRadioButton1.setText(hey[1]);
          jRadioButton5.setText(hey[2]);
          jRadioButton6.setText(hey[3]);
          jRadioButton7.setText(hey[4]);
          if(i==4) jButton1.setText("Submit");
    }
public     static  ButtonGroup group = new ButtonGroup();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TEKWIZ QUIZ");
        setPreferredSize(new java.awt.Dimension(761, 416));

        jTextField1.setEditable(false);
        jTextField1.setText("J");

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("jRadioButton1");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("jRadioButton1");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("jRadioButton1");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jButton1.setText("Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame2().setVisible(true);
            }
        });
    }
public void actionPerformed(ActionEvent a) {

if(a.getSource()==jButton1)
{
        if(page>=4)
    {
         if(correct[page]==true) 
        {
            result++;
        }
         dispose();
Result result = new Result();
result.show();
        return;
    }
        if(correct[page]==true) 
        {                

            result++;  
                }
page++;
        group.clearSelection();

setThisText1(page);

}

if(a.getSource()==jRadioButton1)
{
    if(srabotalo[page] == false)
    {
    if(answers[page]==1) 
    { srabotalo[page] = true;
        correct[page]=true;
    }
    else 
    {
               correct[page]=false; 
    }
    }
}
if(a.getSource()==jRadioButton7)
{
 if(srabotalo[page] == false)
    {
    if(answers[page]==2) 
    { srabotalo[page] = true;
        correct[page]=true;
    }
    else 
    {
               correct[page]=false; 
    }
    }

}
if(a.getSource()==jRadioButton5)
{
 if(srabotalo[page] == false)
    {
    if(answers[page]==3) 
    { srabotalo[page] = true;
        correct[page]=true;
    }
    else 
    {
               correct[page]=false; 
    }
    }

}

if(a.getSource()==jRadioButton6)
{
 if(srabotalo[page] == false)
    {
    if(answers[page]==4) 
    { srabotalo[page] = true;
        correct[page]=true;
    }
    else 
    {
               correct[page]=false; 
    }
    }

}

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private static javax.swing.JRadioButton jRadioButton1;
    private static javax.swing.JRadioButton jRadioButton5;
    private static javax.swing.JRadioButton jRadioButton6;
    private static javax.swing.JRadioButton jRadioButton7;
    private static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

